[package]
name = "try_specs"
version = "0.1.0"
authors = ["Ben-PH <benphawke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = { version = "0.16", features = ["specs-derive"] }
